name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest Docker image
      run: sudo docker pull prabhanjan953/agent:latest

    - name: Stop and remove old container if exists
      run: |
       sudo docker rm -f agent || true

    - name: Run Docker container
      run: sudo docker run -d -p 80:80 --name agent prabhanjan953/agent:latest
