name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Consider adding labels if you have multiple runners
    
    steps:
    - name: Checkout code (optional but recommended)
      uses: actions/checkout@v4
      if: false  # Disabled since you're only pulling an image, but good to have for future extensions

    - name: Pull latest Docker image
      run:  docker pull prabhanjan953/agent:latest
      # Removed sudo - GitHub Actions runners typically don't need it

    - name: Stop and remove old container if exists
      run: |
         docker stop agent || true
         docker rm agent || true

    - name: Run Docker container
      run: |
         docker run -d --name agent -p 80:80 prabhanjan953/agent:latest
